//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kibiomer_app.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marcadores
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Marcador { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> Numero { get; set; }
        public Nullable<double> XValue { get; set; }
        public Nullable<double> YValue { get; set; }
        public Nullable<double> ZValue { get; set; }
    }
}
